//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiyatro_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiyatro_Konusu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiyatro_Konusu()
        {
            this.Tiyatro = new HashSet<Tiyatro>();
        }
    
        public int Id { get; set; }
        public int kategoriId { get; set; }
        public string konu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiyatro> Tiyatro { get; set; }
        public virtual tiyatro_kategori tiyatro_kategori { get; set; }
    }
}
