//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiyatro_Takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiyatro
    {
        public int Id { get; set; }
        public int kategoriId { get; set; }
        public int tiyatro_konu { get; set; }
        public int sahne_turu { get; set; }
        public string aciklama { get; set; }
        public decimal fiyat { get; set; }
        public string tiyatro_adi { get; set; }
        public string seans_saati { get; set; }
    
        public virtual Sahne_Turu Sahne_Turu1 { get; set; }
        public virtual tiyatro_kategori tiyatro_kategori { get; set; }
        public virtual Tiyatro_Konusu Tiyatro_Konusu { get; set; }
    }
}
